apiVersion: v1
kind: ConfigMap
metadata:
  name: balancer
  namespace: default
data:
  config.yaml: |
    schema: http                  # support http and https
    port: 8089                    # port for balancer
    ssl_certificate:
    ssl_certificate_key:
    tcp_health_check: true
    health_check_interval: 3      # health check interval (second)
    # The maximum number of requests that the balancer can handle at the same time
    # 0 refers to no limit to the maximum number of requests
    max_allowed: 100
    location:                     # route matching for reverse proxy
      - pattern: /
        proxy_pass:                   # URL of the reverse proxy
        - "http://192.168.1.1"
        - "http://192.168.1.2:1015"
        - "https://192.168.1.2"
        - "http://my-server.com"
        balance_mode: round-robin     # load balancing algorithm