apiVersion: v1
kind: Service
metadata:
  name: balancer
  namespace: default
spec:
  type: NodePort
  selector:
    app: balancer
  ports:
    - name: balancer
      protocol: TCP
      nodePort: 30089
      port: 80
      targetPort: 8089